#ifndef ERRORS_H
#define ERRORS_H

#define ERROR_TESTING 0
#define ERROR_INVALID_INTEGER 10
#define ERROR_INVALID_FLOAT   20
#define ERROR_INVALID_STRING   30
#define ERROR_INVALID_OPERATOR  40
#define ERROR_INVALID_IDENTIFIER  50
#endif // ERRORS_H
